version: '3'

services:
  spring-boot-docker-app:
    image: spring-boot-docker-image
    build:
      context: ../Spring-Boot-jpa-h2-example
      dockerfile: Dockerfile
    ports:
      - 8080:8181
    volumes:
      - /storage/my-app